// Genere CLQ App Factory v2026.06.25-audio-report-fix-1
const locations=[
    { name: "Grand-Place — Place du Général-de-Gaulle", lat: 50.63685, lng: 3.06315, audio: "audio/Grand_Place_Place_du_General_de_Gaulle.mp3", image: "images/points interets/grand-place-place-du-general-de-gaulle.jpg", fallbackImage: "images/points interets/Grand_Place_Place_du_General_de_Gaulle.svg", remoteImage: "https://upload.wikimedia.org/wikipedia/commons/2/2b/Grand_place%2C_Lille.jpg" },
    { name: "Vieille Bourse", lat: 50.6372, lng: 3.06375, audio: "audio/Vieille_Bourse.mp3", image: "images/points interets/vieille-bourse.jpg", fallbackImage: "images/points interets/Vieille_Bourse.svg", remoteImage: "https://upload.wikimedia.org/wikipedia/commons/9/9d/France-Lille-VieilleBourse-FacadeGrandPlace.jpg" },
    { name: "Opéra de Lille", lat: 50.63760510893339, lng: 3.0655194895197173, audio: "audio/Opera_de_Lille.mp3", image: "images/points interets/opera-de-lille.jpg", fallbackImage: "images/points interets/Opera_de_Lille.svg", remoteImage: "https://upload.wikimedia.org/wikipedia/commons/d/d0/Opera_of_Lille.JPG" },
    { name: "Rue de la Monnaie", lat: 50.64035, lng: 3.0626, audio: "audio/Rue_de_la_Monnaie.mp3", image: "images/points interets/rue-de-la-monnaie.jpg", fallbackImage: "images/points interets/Rue_de_la_Monnaie.svg", remoteImage: "https://upload.wikimedia.org/wikipedia/commons/8/8b/Lille_39_rue_de_la_monnaie.JPG" },
    { name: "Cathédrale Notre Dame de la treille", lat: 50.64019377561323, lng: 3.062670268634871, audio: "audio/Cathedrale_Notre_Dame_de_la_treille.mp3", image: "images/points interets/cathedrale-notre-dame-de-la-treille.jpg", fallbackImage: "images/points interets/Cathedrale_Notre_Dame_de_la_treille.svg", remoteImage: "https://upload.wikimedia.org/wikipedia/commons/6/61/Cath%C3%A9drale_Notre-Dame-de-la-Treille_de_Lille_02.jpg" },
    { name: "Hospice Comtesse", lat: 50.64106, lng: 3.0628, audio: "audio/Hospice_Comtesse.mp3", image: "images/points interets/hospice-comtesse.jpg", fallbackImage: "images/points interets/Hospice_Comtesse.svg", remoteImage: "https://upload.wikimedia.org/wikipedia/commons/0/03/Lille_Hospice_comtesse_Marie_Carton.JPG" },
    { name: "Place aux Oignons", lat: 50.64155, lng: 3.06137, audio: "audio/Place_aux_Oignons.mp3", image: "images/points interets/place-aux-oignons.jpg", fallbackImage: "images/points interets/Place_aux_Oignons.svg", remoteImage: "https://upload.wikimedia.org/wikipedia/commons/d/da/Lille_vue_quai_du_wault.jpg" },
    { name: "Palais Rihour", lat: 50.63605, lng: 3.06195, audio: "audio/Palais_Rihour.mp3", image: "images/points interets/palais-rihour.jpg", fallbackImage: "images/points interets/Palais_Rihour.svg", remoteImage: "https://upload.wikimedia.org/wikipedia/commons/4/49/Lille_Palais_Rihour.jpg" },
    { name: "Église Saint-Maurice", lat: 50.63655, lng: 3.06628, audio: "audio/Eglise_Saint_Maurice.mp3", image: "images/points interets/eglise-saint-maurice.jpg", fallbackImage: "images/points interets/Eglise_Saint_Maurice.svg", remoteImage: "https://upload.wikimedia.org/wikipedia/commons/7/7b/Lille_Saint-Maurice_076.jpg" },
    { name: "Gare Lille-Flandres", lat: 50.6368, lng: 3.07015, audio: "audio/Gare_Lille_Flandres.mp3", image: "images/points interets/gare-lille-flandres.jpg", fallbackImage: "images/points interets/Gare_Lille_Flandres.svg", remoteImage: "https://upload.wikimedia.org/wikipedia/commons/5/5b/Lille_Gare_Flandres.jpg" },
    { name: "Porte de Paris", lat: 50.63188, lng: 3.07041, audio: "audio/Porte_de_Paris.mp3", image: "images/points interets/porte-de-paris.jpg", fallbackImage: "images/points interets/Porte_de_Paris.svg", remoteImage: "https://upload.wikimedia.org/wikipedia/commons/e/e7/Porte_de_Paris_Lille_%281%29.jpg" },
    { name: "Beffroi de Lille", lat: 50.630653793448694, lng: 3.0697719686343836, audio: "audio/Beffroi_de_Lille.mp3", image: "images/points interets/beffroi-de-l-hotel-de-ville.jpg", fallbackImage: "images/points interets/Beffroi_de_Lille.svg", remoteImage: "https://upload.wikimedia.org/wikipedia/commons/b/b3/Lille_Belfried_Blick_auf_Euralille.jpg" },
    { name: "Palais des Beaux Arts", lat: 50.63047436600037, lng: 3.062792797469776, audio: "audio/Palais_des_Beaux_Arts.mp3", image: "images/points interets/palais-des-beaux-arts.jpg", fallbackImage: "images/points interets/Palais_des_Beaux_Arts.svg", remoteImage: "https://upload.wikimedia.org/wikipedia/commons/e/e7/Lille_palais_des_beaux_arts_face_2.jpg" },
    { name: "Muséum d’Histoire Naturelle", lat: 50.62591, lng: 3.0644, audio: "audio/Museum_d_Histoire_Naturelle.mp3", image: "images/points interets/museum-d-histoire-naturelle.jpg", fallbackImage: "images/points interets/Museum_d_Histoire_Naturelle.svg", remoteImage: "https://upload.wikimedia.org/wikipedia/commons/f/fb/Lille_Mus%C3%A9e_histoire_naturelle.jpg" },
    { name: "Gare Saint-Sauveur", lat: 50.62669, lng: 3.068, audio: "audio/Gare_Saint_Sauveur.mp3", image: "images/points interets/gare-saint-sauveur.jpg", fallbackImage: "images/points interets/Gare_Saint_Sauveur.svg", remoteImage: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Lille_gare_saint_sauveur.JPG" },
    { name: "Maison Coilliot", lat: 50.62839, lng: 3.05866, audio: "audio/Maison_Coilliot.mp3", image: "images/points interets/maison-coilliot.jpg", fallbackImage: "images/points interets/Maison_Coilliot.svg", remoteImage: "https://upload.wikimedia.org/wikipedia/commons/9/90/Maison_Coilliot_1.JPG" },
    { name: "Halles de Wazemmes", lat: 50.62636, lng: 3.05204, audio: "audio/Halles_de_Wazemmes.mp3", image: "images/points interets/halles-de-wazemmes.jpg", fallbackImage: "images/points interets/Halles_de_Wazemmes.svg", remoteImage: "https://upload.wikimedia.org/wikipedia/commons/c/c9/Lille_halles_wazemmes.JPG" },
    { name: "Jardin Vauban", lat: 50.6368, lng: 3.0476, audio: "audio/Jardin_Vauban.mp3", image: "images/points interets/jardin-vauban.jpg", fallbackImage: "images/points interets/Jardin_Vauban.svg", remoteImage: "https://upload.wikimedia.org/wikipedia/commons/e/ea/Lille_-_Jardin_Vauban_-_2.jpg" },
    { name: "Citadelle de Lille", lat: 50.6409298715109, lng: 3.0445919263056855, audio: "audio/Citadelle_de_Lille.mp3", image: "images/points interets/citadelle-de-lille.jpg", fallbackImage: "images/points interets/Citadelle_de_Lille.svg", remoteImage: "https://upload.wikimedia.org/wikipedia/commons/f/f4/Grondplan_citadel_Lille.JPG" },
    { name: "Quai du Wault", lat: 50.63749, lng: 3.05425, audio: "audio/Quai_du_Wault.mp3", image: "images/points interets/quai-du-wault.jpg", fallbackImage: "images/points interets/Quai_du_Wault.svg", remoteImage: "https://upload.wikimedia.org/wikipedia/commons/2/21/Lille_quai_du_Wault.jpg" }
];
const availableCircuits=["petit","moyen","grand"];
const circuits={"petit":[1,2,3,4,5,6,7,8,1],"petit_gare":[1,2,3,4,5,6,7,8,1],"moyen":[1,2,3,4,5,6,7,8,9,10,11,12,13,1],"moyen_gare":[1,2,3,4,5,6,7,8,9,10,11,12,13,1],"grand":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,1],"grand_gare":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,1]};
